### ISSUE TITLE
`test_vnc` fails in the `cert-mir-core20-pi-kernel-20-beta-rpi3b-armhf` environment

### ISSUE THREAD

**Issue by mattkae** [canonical/mir-ci#139] opened 2024-07-10 17:37 UTC
This test was added here: https://github.com/canonical/mir-ci/commit/de7bf264df0c882bb2574673c9c2e4ad0d7a45a6#diff-c05c6f247ce8b0236879965274ed5c01f025896294bb5b746b0ad238356b34af

<details>
<summary>Here is the full log</summary>

<pre>
<code>
      dbus-daemon[21096]: [session uid=1000 pid=21096] Activating service name='org.freedesktop.systemd1' requested by ':1.0' (uid=1000 pid=21097 comm="checkbox-mir.mir-ci --verbose --junitxml=/tmp/mir-" label="unconfined")
dbus-daemon[21096]: [session uid=1000 pid=21096] Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.2, pluggy-1.5.0 -- /snap/checkbox-mir/784/bin/python3
cachedir: /tmp/pytest-cache
rootdir: /snap/checkbox-mir/784/lib/python3.10/site-packages/mir_ci
configfile: pytest.ini
plugins: asyncio-0.23.7
asyncio: mode=auto
collecting ... collected 1 item

tests/test_vnc.py::TestVnc::test_vnc[qterminal-mir_test_tools] FAILED    [100%]

=================================== FAILURES ===================================
__________________ TestVnc.test_vnc[qterminal-mir_test_tools] __________________

self = <test_vnc.TestVnc object at 0xb5cb3b50>
robot_log = PosixPath('/tmp/mir-ci_test_vnc[qterminal-mir_test_tools].robot.html')
server = <mir_ci.program.app.App object at 0xb6359358>
app = <mir_ci.program.app.App object at 0xb5cb34d8>
tmp_path = PosixPath('/tmp/pytest-of-ubuntu/pytest-10/test_vnc_qterminal_mir_test_to0')

    @pytest.mark.parametrize("app", (apps.qterminal("--execute", "wayvnc"),))
    async def test_vnc(self, robot_log, server, app, tmp_path) -> None:
        extensions = (ZwlrVirtualPointerManagerV1.name, ZwlrScreencopyManagerV1.name, "zwp_virtual_keyboard_manager_v1")
        server_instance = DisplayServer(server, add_extensions=extensions)
        program = server_instance.program(app)
    
        robot_test_case = dedent(
            """\
            Vnc
                Sleep    1
                HID.Type String    Hello World
                Sleep    1
                # Drag window (assuming a 5:4 aspect ratio output)
                Move Pointer To Proportional (0.5, 0.19)
                Press LEFT Button
                Walk Pointer To Proportional (1, 0.6)
                Release LEFT Button
        """
        )
    
        with tempfile.NamedTemporaryFile(mode="w+", suffix=".robot", buffering=1) as robot_file:
            robot_file.write(ROBOT_TEMPLATE.format(settings=ROBOT_SETTINGS, test_case=robot_test_case))
            robot = server_instance.program(App(("robot", "-d", tmp_path, "--log", robot_log, robot_file.name)))
    
            async with server_instance, program:
                async with robot:
>                   await robot.wait()

tests/test_vnc.py:65: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <mir_ci.program.program.Program object at 0xb5cb3fa0>, timeout = 10
term_timeout = 10

    async def wait(self, timeout=default_wait_timeout, term_timeout=default_term_timeout) -> None:
        if self.is_running():
            self.send_signals_task = asyncio.create_task(self.send_kill_signals(timeout, term_timeout))
        if self.process_end is not None:
            await self.process_end
            self.process_end = None
            print("\n" + format_output(self.name, self.output))
            assert self.process
            if self.process.returncode != 0:
                message = self.name
                if self.sigkill_sent:
                    message += " refused to terminate"
                else:
                    message += " closed with exit code " + str(self.process.returncode)
>               raise ProgramError(message)
E               mir_ci.program.program.ProgramError: robot closed with exit code 1

program/program.py:97: ProgramError
----------------------------- Captured stdout call -----------------------------

╭───────────────────────────────────┤ robot ├──────────────────────────────────
│ Second signal will force exit.
│ 2024-07-10 08:55:27,644 - RPA.core.certificates - INFO - Truststore not in use, HTTPS traffic validated against `certifi` package. (requires Python 3.10.12 and 'pip' 23.2.1 at minimum)
│ ==============================================================================
│ Tmpp9Y7U38M                                                                   
│ ==============================================================================
│ Vnc                                                                   | FAIL |
│ Execution terminated by signal
│ ------------------------------------------------------------------------------
│ Tmpp9Y7U38M                                                           | FAIL |
│ 1 test, 0 passed, 1 failed
│ ==============================================================================
│ Output:  /tmp/pytest-of-ubuntu/pytest-10/test_vnc_qterminal_mir_test_to0/output.xml
│ Log:     /tmp/mir-ci_test_vnc[qterminal-mir_test_tools].robot.html
│ Report:  /tmp/pytest-of-ubuntu/pytest-10/test_vnc_qterminal_mir_test_to0/report.html
╰──────────────────────────────────────────────────────────────────────────────

╭─────────────────────────────────┤ qterminal ├────────────────────────────────
│ Unable to load translator "default"
│ Unable to load translator "default"
│ Unable to load translator "default"
│ Unable to load translator "default"
│ Unable to load translator "default"
╰──────────────────────────────────────────────────────────────────────────────

╭────────────────────────┤ mir-test-tools.demo-server ├────────────────────────
│ [2024-07-10 08:55:15.260356] <information> mirserver: Starting
│ [2024-07-10 08:55:15.277749] < - debug - > mirserver: Discovered object path for current session = /org/freedesktop/login1/session/_333
│ [2024-07-10 08:55:15.290823] < - debug - > mirserver: Failed to set logind session type: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.133" (uid=1000 pid=21181 comm="/snap/mir-test-tools/15857/usr/bin/mir_demo_server" label="snap.mir-test-tools.demo-server (enforce)") interface="org.freedesktop.login1.Session" member="SetType" error name="(unset)" requested_reply="0" destination=":1.0" (uid=0 pid=861 comm="/lib/systemd/systemd-logind " label="unconfined")
│ [2024-07-10 08:55:15.291125] < - debug - > mirserver: Using logind for session management
│ [2024-07-10 08:55:15.291976] <information> mircommon: Loading modules from: /snap/mir-test-tools/15857/usr/lib/arm-linux-gnueabihf/mir/server-platform
│ [2024-07-10 08:55:15.292486] <information> mircommon: Loading module: /snap/mir-test-tools/15857/usr/lib/arm-linux-gnueabihf/mir/server-platform/graphics-gbm-kms.so.22
│ [2024-07-10 08:55:15.292680] <information> mircommon: Loading module: /snap/mir-test-tools/15857/usr/lib/arm-linux-gnueabihf/mir/server-platform/graphics-wayland.so.22
│ [2024-07-10 08:55:15.292812] <information> mircommon: Loading module: /snap/mir-test-tools/15857/usr/lib/arm-linux-gnueabihf/mir/server-platform/renderer-egl-generic.so.22
│ [2024-07-10 08:55:15.292937] <information> mircommon: Loading module: /snap/mir-test-tools/15857/usr/lib/arm-linux-gnueabihf/mir/server-platform/server-virtual.so.22
│ [2024-07-10 08:55:15.293057] <information> mircommon: Loading module: /snap/mir-test-tools/15857/usr/lib/arm-linux-gnueabihf/mir/server-platform/server-x11.so.22
│ [2024-07-10 08:55:15.293183] <information> mircommon: Loading module: /snap/mir-test-tools/15857/usr/lib/arm-linux-gnueabihf/mir/server-platform/input-evdev.so.9
│ [2024-07-10 08:55:15.302575] <information> mirserver: Found display driver: mir:x11 (version 2.17.0)
│ [2024-07-10 08:55:15.302866] <information> mirserver: (Unsupported by system environment)
│ [2024-07-10 08:55:15.302978] <information> mirserver: Found display driver: mir:egl-generic (version 2.17.0)
│ [2024-07-10 08:55:15.303170] <information> mirserver: Found display driver: mir:wayland (version 2.17.0)
│ [2024-07-10 08:55:15.303274] <information> mirserver: (Unsupported by system environment)
│ [2024-07-10 08:55:15.303371] <information> mirserver: Found display driver: mir:gbm-kms (version 2.17.0)
│ [2024-07-10 08:55:15.318913] < - debug - > gbm-kms: Quirks: checking device with devnode: /dev/dri/card0, driver vc4-drm
│ [2024-07-10 08:55:15.551106] < -warning- > gbm-kms: Failed to detect whether device /dev/dri/card0 supports KMS, continuing with lower confidence
│ [2024-07-10 08:55:15.560494] < - debug - > gbm-kms: Quirks: checking device with devnode: (null), driver 
│ [2024-07-10 08:55:15.563346] <information> mirserver: Driver supports:
│ [2024-07-10 08:55:15.563649] <information> mirserver: 	/devices/platform/soc/soc:gpu/drm/card0 (priority 128)
│ [2024-07-10 08:55:15.563782] <information> mirserver: Found display driver: mir:virtual (version 2.17.0)
│ [2024-07-10 08:55:15.563894] <information> mirserver: (Unsupported by system environment)
│ [2024-07-10 08:55:15.564134] <information> mirserver: Selected display driver: mir:gbm-kms (version 2.17.0) for device ((null): /dev/dri/card0)
│ [2024-07-10 08:55:15.619749] <information> mircommon: Loading modules from: /snap/mir-test-tools/15857/usr/lib/arm-linux-gnueabihf/mir/server-platform
│ [2024-07-10 08:55:15.620182] <information> mircommon: Loading module: /snap/mir-test-tools/15857/usr/lib/arm-linux-gnueabihf/mir/server-platform/graphics-gbm-kms.so.22
│ [2024-07-10 08:55:15.620366] <information> mircommon: Loading module: /snap/mir-test-tools/15857/usr/lib/arm-linux-gnueabihf/mir/server-platform/graphics-wayland.so.22
│ [2024-07-10 08:55:15.620479] <information> mircommon: Loading module: /snap/mir-test-tools/15857/usr/lib/arm-linux-gnueabihf/mir/server-platform/renderer-egl-generic.so.22
│ [2024-07-10 08:55:15.620588] <information> mircommon: Loading module: /snap/mir-test-tools/15857/usr/lib/arm-linux-gnueabihf/mir/server-platform/server-virtual.so.22
│ [2024-07-10 08:55:15.620691] <information> mircommon: Loading module: /snap/mir-test-tools/15857/usr/lib/arm-linux-gnueabihf/mir/server-platform/server-x11.so.22
│ [2024-07-10 08:55:15.620794] <information> mircommon: Loading module: /snap/mir-test-tools/15857/usr/lib/arm-linux-gnueabihf/mir/server-platform/input-evdev.so.9
│ [2024-07-10 08:55:15.628609] <information> mirserver: Found rendering driver: mir:gbm-kms (version 2.17.0)
│ [2024-07-10 08:55:15.628806] < - debug - > gbm-kms: GBM-capable display found
│ [2024-07-10 08:55:15.638917] < - debug - > gbm-kms: Quirks: checking device with devnode: /dev/dri/card0, driver vc4-drm
│ [2024-07-10 08:55:15.641267] < - debug - > gbm-kms: Quirks: checking device with devnode: (null), driver 
│ [2024-07-10 08:55:15.643661] < - debug - > gbm-kms: Quirks: checking device with devnode: /dev/dri/renderD128, driver vc4-drm
│ [2024-07-10 08:55:15.687341] <information> mirserver: Driver supports:
│ [2024-07-10 08:55:15.687567] <information> mirserver: 	/devices/platform/soc/soc:gpu/drm/renderD128 (priority 256)
│ [2024-07-10 08:55:15.687681] <information> mirserver: Found rendering driver: mir:wayland (version 2.17.0)
│ [2024-07-10 08:55:15.687889] <information> mirserver: Found rendering driver: mir:egl-generic (version 2.17.0)
│ [2024-07-10 08:55:15.729078] <information> mirserver: Driver supports:
│ [2024-07-10 08:55:15.729214] <information> mirserver: 	System (priority 128)
│ [2024-07-10 08:55:15.729316] <information> mirserver: Found rendering driver: mir:virtual (version 2.17.0)
│ [2024-07-10 08:55:15.729516] <information> mirserver: Found rendering driver: mir:x11 (version 2.17.0)
│ [2024-07-10 08:55:15.729828] <information> mirserver: Selected rendering driver: mir:gbm-kms (version 2.17.0) for device ((null): /dev/dri/renderD128)
│ [2024-07-10 08:55:15.730649] < - debug - > gbm-kms: Checking whether /dev/dri/renderD128 is the same device as (/dev/dri/card0, /dev/dri/renderD128)...
│ [2024-07-10 08:55:15.730738] < - debug - > gbm-kms: 	...yup.
│ [2024-07-10 08:55:15.859945] < - debug - > gbm-kms: No EDID data available on connector 89
│ [2024-07-10 08:55:15.860121] < -warning- > gbm-kms: Unable to determine the current display mode.
│ [2024-07-10 08:55:15.860742] <information> gbm-kms: DRM device details:
│ [2024-07-10 08:55:15.860976] <information> gbm-kms: /dev/dri/card0: using driver vc4 [Broadcom VC4 graphics] (version: 0.0.0 driver date: 20140616)
│ [2024-07-10 08:55:15.861249] <information> gbm-kms: 	Output: DSI-1 (connected)
│ [2024-07-10 08:55:15.861348] <information> gbm-kms: 		Mode: 800×480@60.04
│ [2024-07-10 08:55:15.861813] < -warning- > gbm-kms: Ignoring attempt to set zero length gamma
│ [2024-07-10 08:55:15.864608] < -warning- > miral: Failed to load cursor theme: default
│ [2024-07-10 08:55:15.962600] <information> mirserver: Using hardware cursor
│ [2024-07-10 08:55:15.983131] < -warning- > miral: Failed to load cursor theme: default
│ [2024-07-10 08:55:16.043934] <information> gbm-kms-buffer-allocator: Enabled linux-dmabuf import support
│ [2024-07-10 08:55:16.103796] < - ERROR - > mirserver: Unable to watch directory /snap/mir-test-tools/15857/graphics/usr/share/applications
│ [2024-07-10 08:55:16.105421] <information> mircommon: Loading modules from: /snap/mir-test-tools/15857/usr/lib/arm-linux-gnueabihf/mir/server-platform
│ [2024-07-10 08:55:16.105948] <information> mircommon: Loading module: /snap/mir-test-tools/15857/usr/lib/arm-linux-gnueabihf/mir/server-platform/graphics-gbm-kms.so.22
│ [2024-07-10 08:55:16.106196] <information> mircommon: Loading module: /snap/mir-test-tools/15857/usr/lib/arm-linux-gnueabihf/mir/server-platform/graphics-wayland.so.22
│ [2024-07-10 08:55:16.106342] <information> mircommon: Loading module: /snap/mir-test-tools/15857/usr/lib/arm-linux-gnueabihf/mir/server-platform/renderer-egl-generic.so.22
│ [2024-07-10 08:55:16.106510] <information> mircommon: Loading module: /snap/mir-test-tools/15857/usr/lib/arm-linux-gnueabihf/mir/server-platform/server-virtual.so.22
│ [2024-07-10 08:55:16.106674] <information> mircommon: Loading module: /snap/mir-test-tools/15857/usr/lib/arm-linux-gnueabihf/mir/server-platform/server-x11.so.22
│ [2024-07-10 08:55:16.106808] <information> mircommon: Loading module: /snap/mir-test-tools/15857/usr/lib/arm-linux-gnueabihf/mir/server-platform/input-evdev.so.9
│ [2024-07-10 08:55:16.115385] <information> mirserver: Selected input driver: mir:evdev-input (version: 2.17.0)
│ [2024-07-10 08:55:16.116346] <information> mirserver: Mir version 2.17.0
│ [2024-07-10 08:55:16.140117] <information> GLRenderer: EGL vendor: Mesa Project
│ [2024-07-10 08:55:16.140315] <information> GLRenderer: EGL version: 1.4
│ [2024-07-10 08:55:16.140428] <information> GLRenderer: EGL client APIs: OpenGL OpenGL_ES 
│ [2024-07-10 08:55:16.140561] <information> GLRenderer: EGL extensions: EGL_ANDROID_blob_cache EGL_ANDROID_native_fence_sync EGL_EXT_buffer_age EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_context_flush_control EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_no_config_context EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_image_dma_buf_export EGL_MESA_query_driver EGL_WL_bind_wayland_display 
│ [2024-07-10 08:55:16.140669] <information> GLRenderer: GL vendor: Broadcom
│ [2024-07-10 08:55:16.140764] <information> GLRenderer: GL renderer: VC4 V3D 2.1
│ [2024-07-10 08:55:16.140846] <information> GLRenderer: GL version: OpenGL ES 2.0 Mesa 23.2.1-1ubuntu3.1~22.04.2
│ [2024-07-10 08:55:16.140925] <information> GLRenderer: GLSL version: OpenGL ES GLSL ES 1.0.16
│ [2024-07-10 08:55:16.141126] <information> GLRenderer: GL extensions: GL_EXT_blend_minmax GL_EXT_multi_draw_arrays GL_EXT_texture_compression_s3tc GL_EXT_texture_compression_dxt1 GL_EXT_texture_format_BGRA8888 GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_rgb8_rgba8 GL_OES_stencil8 GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_EGL_image GL_OES_depth_texture GL_AMD_performance_monitor GL_OES_packed_depth_stencil GL_OES_get_program_binary GL_APPLE_texture_max_level GL_EXT_discard_framebuffer GL_EXT_read_format_bgra GL_NV_pack_subimage GL_EXT_frag_depth GL_NV_fbo_color_attachments GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_array_object GL_ANGLE_pack_reverse_row_order GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_EXT_unpack_subimage GL_NV_draw_buffers GL_NV_read_buffer GL_NV_read_depth GL_NV_read_depth_stencil GL_NV_read_stencil GL_EXT_draw_buffers GL_EXT_map_buffer_range GL_KHR_debug GL_KHR_texture_compression_astc_ldr GL_NV_generate_mipmap_sRGB GL_NV_pixel_buffer_object GL_OES_required_internalformat GL_OES_surfaceless_context GL_EXT_debug_label GL_EXT_separate_shader_objects GL_EXT_compressed_ETC1_RGB8_sub_texture GL_EXT_draw_elements_base_vertex GL_EXT_texture_border_clamp GL_KHR_context_flush_control GL_OES_draw_elements_base_vertex GL_OES_texture_border_clamp GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_EXT_texture_compression_s3tc_srgb GL_KHR_parallel_shader_compile GL_MESA_tile_raster_order GL_MESA_bgra 
│ [2024-07-10 08:55:16.141231] <information> GLRenderer: GL max texture size = 2048
│ [2024-07-10 08:55:16.143211] <information> GLRenderer: GL framebuffer bits: RGBA=8880, depth=0, stencil=0
│ [2024-07-10 08:55:16.170310] < - debug - > mirserver: Ignoring logind PauseDevice("gone") event for DRM device 226:0
│ [2024-07-10 08:55:16.170553] <information> mirserver: Initial display configuration:
│ [2024-07-10 08:55:16.170647] <information> mirserver: * Output 1: DSI connected, used
│ [2024-07-10 08:55:16.170732] <information> mirserver: . |_ Physical size 0.0" 0x0mm
│ [2024-07-10 08:55:16.170813] <information> mirserver: . |_ Power is on
│ [2024-07-10 08:55:16.170895] <information> mirserver: . |_ Current mode 800x480 60.04Hz
│ [2024-07-10 08:55:16.170977] <information> mirserver: . |_ Preferred mode 800x480 60.04Hz
│ [2024-07-10 08:55:16.171057] <information> mirserver: . |_ Orientation normal
│ [2024-07-10 08:55:16.171140] <information> mirserver: . |_ Logical size 800x480
│ [2024-07-10 08:55:16.171219] <information> mirserver: . |_ Logical position +0+0
│ [2024-07-10 08:55:16.171296] <information> mirserver: . |_ Scaling factor: 1.00
│ libinput error: /usr/share/libinput: failed to find data files
│ libinput error: Failed to load the device quirks from /usr/share/libinput and /etc/libinput/local-overrides.quirks. This will negatively affect device behavior. See https://wayland.freedesktop.org/libinput/doc/1.20.0/device-quirks.html for details.
│ [2024-07-10 08:55:22.455537] <information> GLRenderer: EGL vendor: Mesa Project
│ [2024-07-10 08:55:22.455810] <information> GLRenderer: EGL version: 1.4
│ [2024-07-10 08:55:22.455949] <information> GLRenderer: EGL client APIs: OpenGL OpenGL_ES 
│ [2024-07-10 08:55:22.456128] <information> GLRenderer: EGL extensions: EGL_ANDROID_blob_cache EGL_ANDROID_native_fence_sync EGL_EXT_buffer_age EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_context_flush_control EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_no_config_context EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_image_dma_buf_export EGL_MESA_query_driver EGL_WL_bind_wayland_display 
│ [2024-07-10 08:55:22.456223] <information> GLRenderer: GL vendor: Broadcom
│ [2024-07-10 08:55:22.456302] <information> GLRenderer: GL renderer: VC4 V3D 2.1
│ [2024-07-10 08:55:22.456377] <information> GLRenderer: GL version: OpenGL ES 2.0 Mesa 23.2.1-1ubuntu3.1~22.04.2
│ [2024-07-10 08:55:22.456452] <information> GLRenderer: GLSL version: OpenGL ES GLSL ES 1.0.16
│ [2024-07-10 08:55:22.456664] <information> GLRenderer: GL extensions: GL_EXT_blend_minmax GL_EXT_multi_draw_arrays GL_EXT_texture_compression_s3tc GL_EXT_texture_compression_dxt1 GL_EXT_texture_format_BGRA8888 GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_rgb8_rgba8 GL_OES_stencil8 GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_EGL_image GL_OES_depth_texture GL_AMD_performance_monitor GL_OES_packed_depth_stencil GL_OES_get_program_binary GL_APPLE_texture_max_level GL_EXT_discard_framebuffer GL_EXT_read_format_bgra GL_NV_pack_subimage GL_EXT_frag_depth GL_NV_fbo_color_attachments GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_array_object GL_ANGLE_pack_reverse_row_order GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_EXT_unpack_subimage GL_NV_draw_buffers GL_NV_read_buffer GL_NV_read_depth GL_NV_read_depth_stencil GL_NV_read_stencil GL_EXT_draw_buffers GL_EXT_map_buffer_range GL_KHR_debug GL_KHR_texture_compression_astc_ldr GL_NV_generate_mipmap_sRGB GL_NV_pixel_buffer_object GL_OES_required_internalformat GL_OES_surfaceless_context GL_EXT_debug_label GL_EXT_separate_shader_objects GL_EXT_compressed_ETC1_RGB8_sub_texture GL_EXT_draw_elements_base_vertex GL_EXT_texture_border_clamp GL_KHR_context_flush_control GL_OES_draw_elements_base_vertex GL_OES_texture_border_clamp GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_EXT_texture_compression_s3tc_srgb GL_KHR_parallel_shader_compile GL_MESA_tile_raster_order GL_MESA_bgra 
│ [2024-07-10 08:55:22.456766] <information> GLRenderer: GL max texture size = 2048
│ [2024-07-10 08:55:22.458471] <information> GLRenderer: GL framebuffer bits: RGBA=8888, depth=0, stencil=0
│ [2024-07-10 08:55:33.773652] < - debug - > mirserver: Handling Terminated from pid=21097
╰──────────────────────────────────────────────────────────────────────────────
---- generated xml file: /tmp/mir-ci_test_vnc[qterminal-mir_test_tools].xml ----
=========================== short test summary info ============================
FAILED tests/test_vnc.py::TestVnc::test_vnc[qterminal-mir_test_tools] - mir_c...
============================== 1 failed in 21.82s ==============================
</code>
</pre>
</details>

**Comment by Saviq** [comment] 2024-07-15 06:38
```
│ Vnc                                                                   | FAIL |
│ Execution terminated by signal
```

This suggests the test needs more time.

It would be good for the test to also log it's killing the process due to a timeout.

**Comment by Saviq** [comment] 2024-09-13 21:24
Duplicate of #138

**Closed by Saviq** 2024-09-13 21:24 UTC
Labels: bug
